version: '3.7'
services:
  web1:
    build:
      context: .
      dockerfile: dockerfile_web
      args:
        - NODE_ENV=local
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - '8069:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  web2:
    # Nuevo servicio web
    build:
      context: .
      dockerfile: dockerfile_web
      args:
        - NODE_ENV=local
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - '8070:8069' # Cambiado al puerto  8070 para evitar conflictos
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  web3:
    # Nuevo servicio web
    build:
      context: .
      dockerfile: dockerfile_web
      args:
        - NODE_ENV=local
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - '8068:8069' # Cambiado al puerto  8070 para evitar conflictos
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  db:
    build:
      context: .
      dockerfile: dockerfile_db
      args:
        - NODE_ENV=local
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
